### PR TITLE
feat: added isIPv4

### LINKED ISSUE #103: isIpv4: check whether provided string is an IP address v 4

### PR DESCRIPTION
**Pull request by ndzhwr**
### Added isIPv4() validator
Added a validator for v4  ip addresses
* [ ] Bug
- [x] Feature
* [ ] Breaking changes

Fixes #103

### CODE REVIEW

**Comment by pacifiquem** [comment]
Great Feature .

**Review by veritem — CHANGES_REQUESTED** [review]
Yoo thanks, this looks really nice. Would you mind adding this new func to docs on README after that this will get merged and published on npm

**Review by veritem — APPROVED** [review]
Thanks

**Comment by ndzhwr** [comment]
> Thanks

My pleasure ! 
Cheers

**Pull request merged**
