### PR TITLE
New features

### PR DESCRIPTION
**Pull request by claranceliberi**
Some features added 
- [x] isAccepted
- [x] isAlpha
- [x] isAlphaWithSpaces
- [x] isAlphaChars
- [x] isArray
- [x] isJSON
- [x] isObject
- [x] isObjectEmpty
- [x] isOjectFromSameType

### CODE REVIEW

**Comment by claranceliberi** [comment]
@PatrickNiyogitare28  what are your thoughts on this, we have not heard anything from the team, hence some features need to be used in our app so you can help us to decide if we have those features in valdie or we have to find another way

**Comment by veritem** [comment]
Hi @claranceliberi  this is super cool, would you mind fixing conflicts so I can merge this one?

**Comment by claranceliberi** [comment]
> Hi @claranceliberi this is super cool, would you mind fixing conflicts so I can merge this one?

sure

**Comment by claranceliberi** [comment]
> Hi @claranceliberi this is super cool, would you mind fixing conflicts so I can merge this one?

some work done

**Review by veritem — APPROVED** [review]

**Comment by veritem** [comment]
Thank you so much 👏

**Pull request merged**
